language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master
go_import_path: github.com/fale/gcsc
before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - golangci-lint run --enable-all --disable wsl
  - go test -v -race ./...
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      go: 1.13.x
